"""empty message

Revision ID: 01e8eaed9263
Revises: d990a390f796
Create Date: 2021-05-16 15:24:20.991647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e8eaed9263'
down_revision = 'd990a390f796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'category')
    # ### end Alembic commands ###
