"""empty message

Revision ID: 4510c826385d
Revises: 17c015074ff4
Create Date: 2021-05-17 00:23:41.068609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4510c826385d'
down_revision = '17c015074ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'teachers', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='unique')
    # ### end Alembic commands ###
