"""empty message

Revision ID: 55c5d1e233ed
Revises: 
Create Date: 2021-05-13 22:18:09.863245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c5d1e233ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Students')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Students',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Students_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('repassword', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Students_pkey'),
    sa.UniqueConstraint('email', name='Students_email_key')
    )
    # ### end Alembic commands ###
