"""empty message

Revision ID: 768a31fb0a7e
Revises: 01e8eaed9263
Create Date: 2021-05-16 22:16:09.812046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768a31fb0a7e'
down_revision = '01e8eaed9263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'name')
    # ### end Alembic commands ###
