"""empty message

Revision ID: d990a390f796
Revises: 812ae0056e89
Create Date: 2021-05-16 13:24:45.444421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd990a390f796'
down_revision = '812ae0056e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('form_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'form_type')
    # ### end Alembic commands ###
